# Site settings
title: International Memento Hackathon 2015 
# email: 
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://MementoHackathon2015.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: MementoHackathon2015

# Build settings
markdown: kramdown
